### ISSUE TITLE
robot.backward() not working

### ISSUE THREAD

**Issue by linzhangUCA** [willward20/the-bot-bros#1]
Tested the motors today. The motors themselves have no problem spinning in either direction. However, when we tried to use the backward() function on PhaseEnableMotor and PhaseEnableRobot, the wheels did not respond well or at all depending on the speed. Cause is uncertain, but we know that the motors are not the problem. It didn't matter which way the motors were wired into the board, forward() function always worked and backward() never worked.

**Comment by linzhangUCA** [comment]
Answer hides [here](https://www.pololu.com/docs/0J72).

**Comment by willward20** [comment]
Solution: make sure the ground pin is connected from Pi to Motor board.
